### ISSUE TITLE
5s is too short of a time limit

### ISSUE THREAD

**Issue by charlieyou** [dubwub/F2016-UPE-AI#1]
Looking through the code: https://github.com/dubwub/F2016-UPE-AI/blob/ce3a56dff8b196ef651bc563484109b9d727d0a3/modules/games/server/controllers/Handler.js#L134

Sometimes I'm not even getting a response back from the competition server that quickly, causing the error "Game ID is undefined..."

**Comment by dubwub** [comment]
Yeah it's just a temporary time limit thing. I was trying to discourage people from just manually playing the game out with their robot by making it a little too tight to do just that, but if people continue having connectivity issues I'll increase the timer.

A balance patch is in the works as well, some of the numbers are going to be tweaked a bit.

**Comment by charlieyou** [comment]
Makes sense, thanks.

**Comment by dubwub** [comment]
I extended the time limit to 15s, I'm going to try to find a better workaround in the future. Quals have also been extended to Nov 20, I'll make a bigger announcement asap
